const DEFAULT_CONFIG = {
  TOKEN_KEY: "TOKEN",

  USER_INFO_KEY: "USER_INFO",

  MENU_KEY: "MENU",

  PERMISSIONS_KEY: "PERMISSIONS",

  APP_LANG_KEY: "APP_LANG",

  APP_THEME_KEY: "APP_DARK",

  APP_LAYOUT_KEY: "APP_LAYOUT",
};

export default DEFAULT_CONFIG;
